version: 2
jobs:
  build:
    working_directory: ~/startup-technology/start-dash
    parallelism: 1
    shell: /bin/bash --login
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          RAILS_ENV: test
          BUNDLE_PATH: vendor/bundle
          YARN_CACHE_FOLDER: ~/.cache/yarn
      - image: circleci/mysql:5.6
        environment:
          MYSQL_DATABASE: circle_test
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: '%'
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - restore_cache:
          keys:
            - rails-bundle-{{ checksum "Gemfile.lock" }}
            - rails-bundle-
      - run: bundle check || bundle install
      - save_cache:
          key: rails-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
            - rails-yarn-{{ checksum "yarn.lock" }}
            - rails-yarn-
      - run: yarn install
      - save_cache:
          key: rails-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: touch .env
      - run: cp -v config/database.ci.yml config/database.yml
      - run: bundle exec rails db:create db:schema:load --trace
      - run: bundle exec rspec --format progress
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
